###
### Website Settings
### => NOTE: Access variables here with: {{site.data.settings.XXXXXXXXX}}
###
siteauthor: '[Travis Peters](https://www.traviswpeters.com/)'

# Instructor-specific variables
school: 'Montana State University'
img: 'assets/me.png'

instructor: '<a target="_blank" href="https://www.traviswpeters.com/">Prof. Travis Peters</a>'
email: '<a target="_blank" href="mailto:travis.peters1@montana.edu?subject=CS 460 Help">travis.peters1@montana.edu</a>'
office: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=342">NAH 253A</a>'
officehours: '<a target="_blank" href="https://montana.webex.com/meet/w52k448">(M) 10am-11am, (W) 3pm-4pm, (F) 9am-10am, and by appointment (via WebEx)</a>'
# officephone: '<a target="_blank" href="tel:4069944296">406-994-4296</a>'

ta: '<a target="_blank" href="https://reesep.github.io">Reese Pearsall</a>'
taemail: '<a target="_blank" href="mailto:reese.pearsall@student.montana.edu?subject=CS 460 Help">reese.pearsall@student.montana.edu</a>'
taoffice: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=342">NAH 253</a>'
# taofficehours: 'TBD and by appointment.'
taofficehours: '<a target="_blank" href="https://montana.webex.com/meet/b37k331">(W) 10am-11am, (Th) 11am-12pm, and by appointment (via WebEx)</a>'

# Course-specific variables
title: 'Operating Systems'
titlenum: 'CS 460'
term: 'Fall 2020'
dates: 'Monday, August 17, 2020 - Wednesday, November ~~18~~ 25, 2020'
textbook: "[Operating Systems: Internals and Design Principles (9th Edition)](https://www.amazon.com/Operating-Systems-Internals-Design-Principles/dp/0134670957), by William Stallings"
finalexamdate: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=3"><i class="fas fa-map-pin"></i> Barnard Hall 108</a> - TBD' #(8:00am - 9:50am) - https://www.montana.edu/registrar/Schedules.html

# --> baseurl set in _config.yml
homeurl: https://www.traviswpeters.com/
url: https://www.traviswpeters.com/cs460-2020-fall/
githuburl: https://github.com/traviswpeters/cs460-2020-fall/

# COURSE LINKS
# <i class="fas fa-external-link-alt"></i>
questionnaire: '[Questionnaire](https://forms.gle/bEMav7XE9h5Nuybg7)'
d2l: '[D2L](https://ecat.montana.edu/d2l/home/622131)'
slack: '[Slack](https://join.slack.com/t/csci460-fa2020/shared_invite/zt-gop7i3kx-8ZwwdQYhyEILOGTSzT_uPA)'
gradescope: '[Gradescope (code: 9RE7N4)](https://www.gradescope.com/courses/141029)'
ssclink: 'https://www.cs.montana.edu/student-success-center.html'
codelink: 'https://github.com/traviswpeters/cs460-code'
zoomlink: 'https://zoom.us/meeting/register/tJYvc--rrzovGt1ohDQhvOV4DWPKvNptgipJ'
webexlink: 'https://montana.webex.com/meet/w52k448'
tawebexlink: 'https://montana.webex.com/meet/b37k331'

# locations of things (notes, slides, etc.)
slides: "files"
notes: "files"
reading: "files"
solutions: "files"
# code: "code"

menu:
- {name: 'About', url: '#about-the-course'}
- {name: 'Logistics', url: '#logistics'}
- {name: 'Schedule', url: '#schedule'}
# - {name: 'Assignments', url: '#assignments'}
# - {name: 'Yalnix', url: 'yalnix'}
# - {name: 'Exams', url: '#exams'}
- {name: 'Resources', url: 'resources'}
- {name: 'FAQs', url: '#faqs'}
- {name: '<span class="text-success">COVID-19 Info</span>', url: 'covid19'}

assignments:
  pa0:
    show: True
    name: 'PA0: Getting Started'
    url: 'pa0'
    duedate: 'Sunday [09/06/2020] @ 11:59 PM (MST)'
  pa1:
    show: False
    name: 'PA1: Procs & Syscalls'
    url: 'pa1'
    duedate: 'Sunday [09/20/2020] @ 11:59 PM (MST)'
  pa2:
    show: False
    name: 'PA2: Concurrency'
    url: 'pa2'
    duedate: 'Sunday [10/04/2020] @ 11:59 PM (MST)'

yalnix:
  link: 'yalnix'
  signuplink: 'https://docs.google.com/spreadsheets/d/10l4tUyOCdWaOeW11HN7hy0Ps4-jy9oC9iaI3rFyZlgg/edit?usp=sharing'
  cp1:
    show: True
    name: 'Checkpoint 1'
    duedate: 'Sunday [10/11/2020] @ 11:59 PM (MST)'
    rubric: ''
  cp2:
    show: True
    name: 'Checkpoint 2'
    duedate: 'Sunday [10/18/2020] @ 11:59 PM (MST)'
    rubric: ''
  cp3:
    show: True
    name: 'Checkpoint 3'
    duedate: 'Sunday [10/25/2020] @ 11:59 PM (MST)'
    rubric: ''
  cp4:
    show: True
    name: 'Checkpoint 4'
    duedate: 'Sunday [11/01/2020] @ 11:59 PM (MST)'
    rubric: ''
  cp5:
    show: True
    name: 'Checkpoint 5'
    duedate: 'Sunday [11/08/2020] @ 11:59 PM (MST)'
    rubric: ''
  cp6:
    show: True
    name: 'Checkpoint 6'
    duedate: 'Sunday [11/15/2020] @ 11:59 PM (MST)'
    rubric: ''
  final:
    show: True
    name: 'Final Yalnix Submission'
    duedate: 'Wednesday [11/18/2020] @ 11:59 PM (MST)'
    rubric: ''

# project:
#   pages:
#     details: "Project Details"
#     schedule: "Project Teams & Schedule"
#   infolink:   'https://docs.google.com/spreadsheets/d/1uMk0pcho_B2v8_7t_E3S-IpsdUfhjBKsT5XdBcfPOBI/edit?usp=sharing'
#   signuplink: 'https://docs.google.com/spreadsheets/d/1uMk0pcho_B2v8_7t_E3S-IpsdUfhjBKsT5XdBcfPOBI/edit?usp=sharing'
#   attendance: 'https://docs.google.com/spreadsheets/d/1ViB-YF5SGXbf1jsXAIPJ-kK7-b3QskZJt4G-cYMuH9s/edit?usp=sharing'
#   rubric:     'https://docs.google.com/spreadsheets/d/1-i5t_Pu6qY2crSkh_R75qNOcRqQeNVmiTlRtsDGFDd0/edit?usp=sharing'
#   rubricpdf:  'rubric.pdf'
#   due-proposal: 'Friday, November 1st, 2019 @10pm'
#   due-final: '~~Friday, December 6th, 2019 @10pm~~ **Thursday, December 12th, 2019 @10pm**{:.text-danger}'
