###
### Website Settings
### => NOTE: Access variables here with: {{site.data.settings.XXXXXXXXX}}
###
siteauthor: '[Travis Peters](https://www.traviswpeters.com/)'

# Instructor-specific variables
school: 'Montana State University'
img: 'assets/me.png'

instructor: '<a target="_blank" href="https://www.traviswpeters.com/">Prof. Travis Peters</a>'
email: '<a target="_blank" href="mailto:travis.peters1@montana.edu?subject=CS 460 Help">travis.peters1@montana.edu</a>'
office: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=342">NAH 253A</a>'
officehours: 'TBD and by appointment.'
officephone: '<a target="_blank" href="tel:4069944296‬">406-994-4296‬</a>'

ta: '<a target="_blank" href="https://reesep.github.io">Reese Pearsall</a>'
taemail: '<a target="_blank" href="mailto:reese.pearsall@student.montana.edu?subject=CS 460 Help">reese.pearsall@student.montana.edu</a>'
taoffice: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=342">NAH 253</a>'
taofficehours: 'TBD and by appointment.'

# Course-specific variables
title: 'Operating Systems'
titlenum: 'CS 460'
term: 'Fall 2020'
dates: 'Monday, August 17, 2020 - Wednesday, November ~~18~~ 25, 2020'
textbook: "[Operating Systems: Internals and Design Principles (9th Edition)](https://www.amazon.com/Operating-Systems-Internals-Design-Principles/dp/0134670957), by William Stallings"
finalexamdate: '<a target="_blank" href="https://www.montana.edu/calendar/locations.php?building=3"><i class="fas fa-map-pin"></i> Barnard Hall 108</a> - TBD' #(8:00am - 9:50am) - https://www.montana.edu/registrar/Schedules.html

# --> baseurl set in _config.yml
homeurl: https://www.traviswpeters.com/
url: https://www.traviswpeters.com/cs460-2020-fall/
githuburl: https://github.com/traviswpeters/cs460-2020-fall/

# COURSE LINKS
# <i class="fas fa-external-link-alt"></i>
questionnaire: '[Questionnaire](https://forms.gle/bEMav7XE9h5Nuybg7)'
d2l: '[D2L](https://ecat.montana.edu/d2l/home/606493)'
slack: '[Slack](https://join.slack.com/t/csci460-fa2020/shared_invite/zt-gop7i3kx-8ZwwdQYhyEILOGTSzT_uPA)'
gradescope: '[Gradescope (code: 9RE7N4)](https://www.gradescope.com/courses/141029)'
ssclink: 'https://www.cs.montana.edu/student-success-center.html'
codelink: 'https://github.com/traviswpeters/cs460-code'
zoomlink: 'https://zoom.us/meeting/register/tJYvc--rrzovGt1ohDQhvOV4DWPKvNptgipJ'

# locations of things (notes, slides, etc.)
slides: "files"
notes: "files"
reading: "files"
solutions: "files"
# code: "code"

menu:
- {name: 'About', url: '#about-the-course'}
- {name: 'Logistics', url: '#logistics'}
- {name: 'Schedule', url: '#schedule'}
# - {name: 'Labs', url: 'labs'}
# - {name: 'Yalnix', url: 'yalnix'}
# - {name: 'Exams', url: '#exams'}
- {name: 'Resources', url: 'resources'}
- {name: 'FAQs', url: '#faqs'}
- {name: '<span class="text-success">COVID-19 Info</span>', url: 'covid19'}

work:
  pa0:
    link: 'pa0'
    duedate: 'Saturday [08/29/2020] @ 11:59 PM (MST)'
  pa1:
    link: 'pa1'
    duedate: 'Saturday [09/05/2020] @ 11:59 PM (MST)'
  pa2:
    link: 'pa2'
    duedate: 'Saturday [09/12/2020] @ 11:59 PM (MST)'

yalnix:
  link: 'yalnix'
  cp1:
    duedate: 'Saturday [09/19/2020] @ 11:59 PM (MST)'
  cp2:
    duedate: 'Saturday [09/26/2020] @ 11:59 PM (MST)'
  cp3:
    duedate: 'Saturday [10/03/2020] @ 11:59 PM (MST)'
  cp4:
    duedate: 'Saturday [10/10/2020] @ 11:59 PM (MST)'
  cp5:
    duedate: 'Saturday [10/17/2020] @ 11:59 PM (MST)'
  cp6:
    duedate: 'Saturday [10/24/2020] @ 11:59 PM (MST)'
  final:
    duedate: 'Saturday [10/31/2020] @ 11:59 PM (MST)'

# project:
#   pages:
#     details: "Project Details"
#     schedule: "Project Teams & Schedule"
#   infolink:   'https://docs.google.com/spreadsheets/d/1uMk0pcho_B2v8_7t_E3S-IpsdUfhjBKsT5XdBcfPOBI/edit?usp=sharing'
#   signuplink: 'https://docs.google.com/spreadsheets/d/1uMk0pcho_B2v8_7t_E3S-IpsdUfhjBKsT5XdBcfPOBI/edit?usp=sharing'
#   attendance: 'https://docs.google.com/spreadsheets/d/1ViB-YF5SGXbf1jsXAIPJ-kK7-b3QskZJt4G-cYMuH9s/edit?usp=sharing'
#   rubric:     'https://docs.google.com/spreadsheets/d/1-i5t_Pu6qY2crSkh_R75qNOcRqQeNVmiTlRtsDGFDd0/edit?usp=sharing'
#   rubricpdf:  'rubric.pdf'
#   due-proposal: 'Friday, November 1st, 2019 @10pm'
#   due-final: '~~Friday, December 6th, 2019 @10pm~~ **Thursday, December 12th, 2019 @10pm**{:.text-danger}'
